version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/nitro-note
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./src:/app/src
      - ./build/libs:/app/build/libs
      - ./gradle:/app/gradle
      - ./gradlew:/app/gradlew
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nitro-note
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
