version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: tramway.proxy.rlwy.net:11441
      SPRING_DATASOURCE_USERNAME: railway
      SPRING_DATASOURCE_PASSWORD: WMsCMRyWjaZZtGzPxzmXRpkXWhjgKbxJ
    volumes:
      - ./src:/app/src
      - ./build/libs:/app/build/libs
      - ./gradle:/app/gradle
      - ./gradlew:/app/gradlew
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: railway
      POSTGRES_PASSWORD: WMsCMRyWjaZZtGzPxzmXRpkXWhjgKbxJ
    ports:
      - "5432:5432"
